apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: LoadBalancer
  ports:
    - name: default
      port: 80
      targetPort: 1234
      protocol: TCP
  selector:
    app: hs-pizza-frontend
