apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-checker
  labels:
    app: health-checker
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: health-checker
  template:
    metadata:
      labels:
        app: health-checker
    spec:
      containers:
        - name: health-checker-pod
          image: ponderosa/hs-pizza-health-checker-service:latest
          ports:
            - containerPort: 5000
          env:
            - name: TOPPING_SUGGESTION_URL
              value: http://topping-suggestion-service
            - name: FRONTEND_URL
              value: http://frontend
