apiVersion: v1
kind: Service
metadata:
  name: health-checker
spec:
  ports:
    - name: default
      port: 80
      targetPort: 1234
      protocol: TCP
  selector:
    app: health-checker
  type: LoadBalancer
