apiVersion: v1
kind: Pod
metadata:
  name: hs-pizza-topping-suggestion
spec:
  containers:
  - name: hs-pizza-topping-suggestion-container
    image: ponderosa/hs-pizza-topping-suggestion:latest
    imagePullPolicy: Always
    ports:
    - containerPort: 5678