apiVersion: v1
kind: Service
metadata:
  name: topping-suggestion-service
spec:
  type: ClusterIP
  ports:
    - name: default
      port: 80
      targetPort: 5678
      protocol: TCP
  selector:
    app: hs-pizza-topping-suggestion