apiVersion: v1
kind: Pod
metadata:
  name: utility
  labels:
    best_pasta_shape: "rigatoni"
spec:
  containers:
  - name: utility
    image: ponderosa/hs-pizza-health-checker
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]
