apiVersion: v1
kind: Service
metadata:
  name: frontend-via-clusterip
spec:
  ports:
  - name: default
    port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: kubernetes-101-frontend
