apiVersion: v1
kind: Service
metadata:
  name: frontend-via-nodeport
spec:
  type: NodePort
  ports:
  - name: default
    port: 80
    targetPort: 80
    protocol: TCP
    nodePort: 30999
  selector:
    app: wat
