apiVersion: v1
kind: Pod
metadata:
  name: utility
  labels:
    best_pasta_shape: "rigatoni"
    best_topping: "artichoke"
spec:
  containers:
  - name: utility
    image: debian:buster-slim
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]
