apiVersion: v1
kind: Service
metadata:
  name: frontend-via-load-balancer
spec:
  type: LoadBalancer
  ports:
  - name: default
    port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: wat
