apiVersion: v1
kind: Pod
metadata:
  name: topping-combo-suggester-manual
  labels:
    app: topping-combo-suggester
spec:
  containers:
  - name: topping-combo-suggester-pod
    image: ponderosa.io/topping-combo-suggester