apiVersion: v1
kind: Service
metadata:
  name: topping-combo-suggester-service
spec:
  ports:
  - name: default
    port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: topping-combo-suggester
